name: Build and Release [Beta]

on:
  workflow_dispatch: # Just to run it manually. You should have seen my older version which requires me to change a text document.
  push:
    paths:
    - 'src/**' # The source code directory is usually different. This is the most basic
    - 'pom.xml'
    - '.github/workflows/build-release.yml' # Make sure this is the same as the file name

permissions:
  contents: write # Let the actions runner to have write access to the repository
  # Might get hacked but it's only going to last for the duration of the workflow. Besides, it's hard.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
  
    - name: Cache Dependencies
      id: cache-dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven
    
    - name: Set up Java Environment
      uses: actions/setup-java@v4
      with:
        java-version: 19
        distribution: 'temurin'
        cache: 'maven'

    - name: Build and Test
      run: mvn clean package install # Sometimes it is something else! Make sure to look hard enough!
      continue-on-error: true # So it uploads dev_env.zip
    
    # Get the short commit SHA to mark versions, search releases by commit
    - name: Set outputs
      id: short_sha
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Archive Repository
      run: |
        # Create a zip file of the entire repository contents
        zip -r dev_env.zip .
    
    - name: Deploy to GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Project-${{ steps.short_sha.outputs.sha_short }}
        path: target/*.jar
      continue-on-error: true
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dev_env-${{ steps.vars.outputs.sha_short }}
        path: dev_env.zip
      continue-on-error: true
    
    - name: Publish Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/*.jar
          dev_env.zip
        body: |
          Commit ${{ steps.short_sha.outputs.sha_short }}
          This release is automatically compiled by GitHub Actions
        name: Project Automation Compile ${{ steps.short_sha.outputs.sha_short }}
        draft: false
        tag_name: commit-${{ steps.short_sha.outputs.sha_short }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_KEY }}
        GITHUB_REPOSITORY: MediumCraft/Project
      continue-on-error: true # So it doesn't fail when files get too large
